name: LeetCode C/C++ CI

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C/C++ compiler
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Compile code
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run basic checks
      run: |
        cd build
        for file in ../*.cpp ../*.c; do
          if [ -f "$file" ]; then
            ./$(basename "$file" .cpp) || ./$(basename "$file" .c)
          fi
        done
